### ISSUE TITLE
test crashes

### ISSUE THREAD

**Issue by kallisti5** [nielx/haiku-rs#1]
```
cargo test
   Compiling cfg-if v1.0.0
   Compiling ppv-lite86 v0.2.15
   Compiling unicode-width v0.1.9
   Compiling remove_dir_all v0.5.3
warning: anonymous parameters are deprecated and will be removed in the next edition.
  --> src/support/flattenable.rs:32:15
   |
32 |     fn unflatten(&[u8]) -> Result<T>;
   |                  ^^^^^ help: try naming the parameter or explicitly ignoring it: `_: &[u8]`
   |
   = note: `#[warn(anonymous_parameters)]` on by default
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2018!
   = note: for more information, see issue #41686 <https://github.com/rust-lang/rust/issues/41686>

warning: `haiku` (lib) generated 1 warning
   Compiling getrandom v0.2.3
   Compiling getopts v0.2.21
   Compiling rand_core v0.6.3
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.4
   Compiling tempfile v3.2.0
   Compiling haiku v0.2.0 (/Data/haiku-rs)
warning: `haiku` (lib test) generated 1 warning (1 duplicate)
    Finished test [unoptimized + debuginfo] target(s) in 15.87s
     Running unittests (target/debug/deps/haiku-a7dc1e5b570ecd30)

running 19 tests
test app::application::tests::looper_test ... FAILED
test app::message::test_message_add_and_remove ... ok
test app::message::test_message_flattening ... FAILED
test app::message::test_message_replace ... ok
test app::message::test_system_message ... ok
test app::messenger::test_messenger_creation ... ok
test app::messenger::test_synchronous_message_sending ... FAILED
test app::notification::tests::test_notification ... FAILED
test app::roster::test_roster_get_app_list ... ok
test app::serverlink::test_link_sender_receiver_behaviour ... ok
test app::serverlink::test_server_link ... ok
test kernel::test_basic_port ... ok
test kernel::test_find_port ... ok
test kernel::test_port_with_timeout ... ok
test storage::attributes::test::test_attribute_ext ... ok
test storage::mimetype::test_mimetype_check ... ok
test storage::mimetype::test_mimetype_methods ... ok
test storage::sys::test_entry_ref_from_path ... ok
test support::flattenable::test_flattenable_primitives ... ok

failures:

---- app::application::tests::looper_test stdout ----
thread 'main' panicked at 'attempted to zero-initialize type `haiku_sys::image_info`, which is invalid', /mnt/d/Rust/rust-x86/library/core/src/mem/mod.rs:628:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- app::message::test_message_flattening stdout ----
thread 'main' panicked at 'attempted to zero-initialize type `haiku_sys::thread_info`, which is invalid', /mnt/d/Rust/rust-x86/library/core/src/mem/mod.rs:628:9

---- app::messenger::test_synchronous_message_sending stdout ----
thread 'main' panicked at 'attempted to zero-initialize type `haiku_sys::thread_info`, which is invalid', /mnt/d/Rust/rust-x86/library/core/src/mem/mod.rs:628:9

---- app::notification::tests::test_notification stdout ----
thread 'main' panicked at 'attempted to zero-initialize type `haiku_sys::image_info`, which is invalid', /mnt/d/Rust/rust-x86/library/core/src/mem/mod.rs:628:9


failures:
    app::application::tests::looper_test
    app::message::test_message_flattening
    app::messenger::test_synchronous_message_sending
    app::notification::tests::test_notification

test result: FAILED. 15 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.01s

error: test failed, to rerun pass '--lib'
```

**Comment by nielx** [comment]
I have some newer work on my machine, I will get it cleaned up and upload it.
